### ISSUE TITLE
Add link to Strava activities

### ISSUE THREAD

**Issue by patfelst** [craibo/ha_strava#96]
Hi there - thanks for this great integration. Enhancement request: Would it be possible to create a sensor that has a web link to the strava activty? So you can click on it in HA and be taken to the Strava website to view futher details. 

e.g. https://www.strava.com/activities/8959343949

Thanks!

**Comment by craibo** [comment]
Hi @patfelst 

The activity id has been added to the title sensor attributes. You can use a template to create the url for now until I get a chance to add the full url to the attributes

**Comment by patfelst** [comment]
Thanks for adding `activity_url` attribute. I'm still struggling with how to display it on the front end so it's clickable. Do you have an example pls? I tried this, but it seems you can't template entities with a type of url:
```yaml
title: Strava
type: entities
entities:
  - type: weblink
    url: '{{ state_attr('sensor.strava_0_0', 'activity_url') }}'
```
